CREATE TABLE elevator_demands (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    floor INTEGER
);

CREATE TABLE elevator_states (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    floor INTEGER,
    vacant BOOLEAN
);
